trigger:
  branches:
    include:
    - main

pool: latestagent

stages:
- stage: Test
  displayName: 'Run Tests and Generate Reports'
  jobs:
  - job: RunTests
    steps:
    - checkout: self
      clean: true

    - script: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt pytest-html
        echo "##vso[task.prependpath]$(pwd)/venv/bin"
      displayName: 'Setup Python with venv'

    - script: |
        mkdir -p test-reports
        echo "Created test-reports directory"
      displayName: 'Create reports directory'

    - script: |
        source venv/bin/activate
        python -m pytest tests/ -v --junitxml=test-reports/test-results.xml --html=test-reports/report.html --self-contained-html
      displayName: 'Run tests with HTML report'

    - task: PublishTestResults@2
      inputs:
        testRunner: 'JUnit'
        testResultsFiles: 'test-reports/test-results.xml'
      displayName: 'Publish test results'

    - script: |
        source venv/bin/activate
        echo "Generating CSV test report..."
        python generate_csv_report.py
      displayName: 'Generate CSV test report'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'test-reports'
        artifactName: 'HTMLTestReports'
      displayName: 'Publish HTML reports'

- stage: Approval
  displayName: '🛑 Manual Approval Required'
  dependsOn: Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: WaitForApproval
    displayName: 'Wait for manual approval'
    pool: server  # ← REQUIRED for ManualValidation
    timeoutInMinutes: 43200  # 30 days timeout
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: |
          approver1@yourcompany.com
          approver2@yourcompany.com
          # Add actual approver email addresses here
        instructions: 'All tests passed! ✅ Please review the HTMLTestReports artifact and approve for deployment.'
        onTimeout: 'reject'

- stage: Deploy
  displayName: '🚀 Deploy to Production'
  dependsOn: Approval
  condition: succeeded()
  jobs:
  - job: Deploy
    pool: latestagent
    steps:
    - download: current
      artifact: HTMLTestReports
      displayName: 'Download test artifacts '
    
    - script: |
        echo "=== STARTING DEPLOYMENT ==="
        echo "All tests passed and manual approval granted!"
        echo "Deploying to production..."
        # Add your actual deployment commands here
        # Example:
        # az webapp deploy --name your-app --src-path ./package.zip
        echo "Deployment completed successfully! 🎉"
      displayName: 'Deploy application'