trigger:
  branches:
    include:
    - main
    - feature/*
    - develop

pool:
  vmImage: latestagent  # Changed to standard Azure DevOps pool syntax

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt pytest-html
  displayName: 'Setup Python with venv'

- script: |
    mkdir -p test-reports
    echo "Created test-reports directory"
  displayName: 'Create reports directory'

- script: |
    source venv/bin/activate
    python -m pytest tests/ -v --junitxml=test-reports/test-results.xml --html=test-reports/report.html --self-contained-html
  displayName: 'Run tests with HTML report'
  continueOnError: true

- script: |
    source venv/bin/activate
    echo "Generating CSV test report..."
    python -c "
import csv
import xml.etree.ElementTree as ET
from datetime import datetime

try:
    tree = ET.parse('test-reports/test-results.xml')
    root = tree.getroot()

    with open('test-reports/test-results.csv', 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(['Test Name', 'Status', 'Duration (seconds)', 'Timestamp', 'Error Message'])
        
        for testcase in root.findall('.//testcase'):
            test_name = testcase.get('name', '')
            class_name = testcase.get('classname', '')
            full_name = f'{class_name}.{test_name}' if class_name else test_name
            duration = testcase.get('time', '0')
            
            if testcase.find('failure') is not None:
                status = 'FAILED'
                error_msg = testcase.find('failure').get('message', 'Assertion Error')
            elif testcase.find('error') is not None:
                status = 'ERROR' 
                error_msg = testcase.find('error').get('message', 'Runtime Error')
            else:
                status = 'PASSED'
                error_msg = ''
            
            writer.writerow([full_name, status, duration, datetime.now().strftime('%Y-%m-%d %H:%M:%S'), error_msg])

    print('CSV report generated: test-reports/test-results.csv')
except Exception as e:
    print(f'Error generating CSV report: {e}')
    exit(1)
"
  displayName: 'Generate CSV test report'

- task: PublishTestResults@2
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: 'test-reports/test-results.xml'
  displayName: 'Publish test results'

- script: |
    echo "=== CHECKING GENERATED FILES ==="
    pwd
    ls -la
    echo "=== TEST-REPORTS CONTENTS ==="
    ls -la test-reports/
    echo "=== CHECKING IF FILES EXIST ==="
    [ -f "test-reports/test-results.xml" ] && echo "test-results.xml exists" || echo "test-results.xml missing"
    [ -f "test-reports/test-results.csv" ] && echo "test-results.csv exists" || echo "test-results.csv missing"
    [ -f "test-reports/report.html" ] && echo "report.html exists" || echo "report.html missing"
  displayName: 'Debug Generated Files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'test-reports'
    artifactName: 'HTMLTestReports'
  displayName: 'Publish HTML reports'