trigger:
  branches:
    include:
    - main
    - feature/*

pool: latestagent

stages:
- stage: Test
  displayName: 'Run Tests and Generate Reports'
  jobs:
  - job: RunTests
    steps:
    - checkout: self

    - script: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install --upgrade pip
        pip3 install -r requirements.txt pytest-html
      displayName: 'Setup Python with venv'

    - script: |
        mkdir -p test-reports
        echo "Created test-report directory"
      displayName: 'Create reports directory'

    - script: |
        source venv/bin/activate
        python -m pytest tests/ -v --junitxml=test-reports/test-results.xml --html=test-reports/report.html --self-contained-html
      displayName: 'Run tests with HTML reports'

    - script: |
        source venv/bin/activate
        echo "Generating CSV test report..."
        python generate_csv_report.py
      displayName: 'Generate CSV test report'

    - task: PublishTestResults@2
      inputs:
        testRunner: 'JUnit'
        testResultsFiles: 'test-reports/test-results.xml'
      displayName: 'Publish test results'

    - script: |
        echo "=== CHECKING GENERATED FILES ==="
        pwd
        ls -la
        echo "=== TEST-REPORTS CONTENTS ==="
        ls -la test-reports/
        echo "=== CHECKING IF FILES EXIST ==="
        [ -f "test-reports/test-results.xml" ] && echo "test-results.xml exists" || echo "test-results.xml missing"
        [ -f "test-reports/test-results.csv" ] && echo "test-results.csv exists" || echo "test-results.csv missing"
        [ -f "test-reports/report.html" ] && echo "report.html exists" || echo "report.html missing"
      displayName: 'Debug Generated Files'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'test-reports'
        artifactName: 'HTMLTestReports'
      displayName: 'Publish HTML reports'

- stage: Approval
  displayName: '🛑 Deployment Approval'
  dependsOn: Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: WaitForApproval
    displayName: 'Wait for manual approval'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "🎉 ALL TESTS PASSED! 100% SUCCESS RATE"
              echo "This is MAIN BRANCH - Manual approval required before any deployment"
              echo "Please review the test reports in HTMLTestReports artifact"
              echo "Click 'Resume' in Azure DevOps to approve and continue"
            displayName: 'Approval pending - All tests passed'