steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Setup Python using Azure task
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Step 3: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Step 4: Run tests
- script: |
    python -m pytest tests/ --junitxml=test-results.xml
  displayName: 'Run Tests'