trigger:
  branches:
    include:
    - main

pool: latestagent

steps:
- checkout: self

- script: |
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt pytest-html
    echo "##vso[task.prependpath]$(pwd)/venv/bin"
  displayName: 'Setup Python with venv'

# Create test-reports directory first
- script: |
    mkdir -p test-reports
    echo "Created test-reports directory"
  displayName: 'Create reports directory'

- script: |
    source venv/bin/activate
    python -m pytest tests/ -v --junitxml=test-results.xml --html=test-reports/report.html --self-contained-html
  displayName: 'Run tests with HTML report'

- task: PublishTestResults@2
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: 'test-results.xml'
  displayName: 'Publish test results'

# Debug: Check what files exist
- script: |
    echo "=== CHECKING GENERATED FILES ==="
    pwd
    ls -la
    echo "=== TEST-REPORTS CONTENTS ==="
    ls -la test-reports/
  displayName: 'Debug Generated Files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'test-reports'
    artifactName: 'HTMLTestReports'
  displayName: 'Publish HTML reports'

    # Add this at the end of your current YAML (no stages needed):
- script: |
    echo "#############################################"
    echo "🛑 MANUAL INTERVENTION REQUIRED"
    echo "#############################################"
    echo "All tests passed successfully!"
    echo "Please check the test reports in HTMLTestReports artifact"
    echo "Then manually resume this pipeline in Azure DevOps UI"
    echo "#############################################"
  condition: succeeded()
  displayName: '🛑 Manual Check Required -Resume Pipeline'