trigger:
  branches:
    include:
    - main
    - feature/*
    - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt pytest-html
  displayName: 'Setup Python with venv'

- script: |
    mkdir -p test-reports
    echo "Created test-reports directory"
  displayName: 'Create reports directory'

- script: |
    source venv/bin/activate
    python -m pytest tests/ -v --junitxml=test-reports/test-results.xml --html=test-reports/report.html --self-contained-html
  displayName: 'Run tests with HTML report'
  continueOnError: true

- script: |
    source venv/bin/activate
    echo "Generating CSV test report..."
    python generate_csv_report.py
  displayName: 'Generate CSV test report'

- task: PublishTestResults@2
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: 'test-reports/test-results.xml'
  displayName: 'Publish test results'

- script: |
    echo "=== CHECKING GENERATED FILES ==="
    pwd
    ls -la
    echo "=== TEST-REPORTS CONTENTS ==="
    ls -la test-reports/
    echo "=== CHECKING IF FILES EXIST ==="
    [ -f "test-reports/test-results.xml" ] && echo "test-results.xml exists" || echo "test-results.xml missing"
    [ -f "test-reports/test-results.csv" ] && echo "test-results.csv exists" || echo "test-results.csv missing"
    [ -f "test-reports/report.html" ] && echo "report.html exists" || echo "report.html missing"
  displayName: 'Debug Generated Files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'test-reports'
    artifactName: 'HTMLTestReports'
  displayName: 'Publish HTML reports'