trigger:
  branches:
    include:
    - main

pool: latestagent

steps:
- checkout: self

- script: |
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt pytest-html
    echo "##vso[task.prependpath]$(pwd)/venv/bin"
  displayName: 'Setup Python with venv'

- script: |
    source venv/bin/activate
    python -m pytest tests/ -v --junitxml=test-results.xml --html=test-reports/report.html --self-contained-html
  displayName: 'Run tests with HTML report'

- task: PublishTestResults@2
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: 'test-results.xml'
  displayName: 'Publish test results'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'test-reports'
    artifactName: 'HTMLTestReports'
  displayName: 'Publish HTML reports'