trigger:
  branches:
    include:
    - main

pool: latestagent

steps:
- checkout: self

- script: |
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt pytest-html
    echo "##vso[task.prependpath]$(pwd)/venv/bin"
  displayName: 'Setup Python with venv'

- script: |
    mkdir -p test-reports
    echo "Created test-reports directory"
  displayName: 'Create reports directory'

- script: |
    source venv/bin/activate
    python -m pytest tests/ -v --junitxml=test-results.xml --html=test-reports/report.html --self-contained-html
  displayName: 'Run tests with HTML report'

# publish test results
# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '**/TEST-*.xml'
- task: PublishTestResults@2
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: 'test-results.xml'
  displayName: 'Publish test results'

- script: |
    echo "=== CHECKING GENERATED FILES ==="
    pwd
    ls -la
    echo "=== TEST-REPORTS CONTENTS ==="
    ls -la test-reports/
  displayName: 'Debug Generated Files'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'test-reports'
    artifactName: 'HTMLTestReports'
  displayName: 'Publish HTML reports'

#choose artifact
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'

